
version: '3.8'

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: always
    network_mode: host
    # ports:
    #   - "3000:8080"
    volumes:
      - open-webui:/app/backend/data
    # extra_hosts:
    #   - host.docker.internal:host-gateway
    environment:
      - OLLAMA_BASE_URL=http://127.0.0.1:11434
      # - OLLAMA_BASE_URL=http://host.docker.internal:11434

volumes:
  open-webui:

# docker run -d -p 3000:8080 --gpus=all -v ollama:/root/.ollama -v open-webui:/app/backend/data --name open-webui --restart always ghcr.io/open-webui/open-webui:ollama
