# Generated by Django 5.2.4 on 2025-08-01 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='top_k',
            field=models.PositiveSmallIntegerField(default=5, help_text='Sample from the k most likely next tokens at each step.'),
        ),
        migrations.AlterField(
            model_name='run',
            name='top_p',
            field=models.FloatField(default=0.7, help_text='The cumulative probability cutoff for token selection.'),
        ),
    ]
