# Generated by Django 5.2.4 on 2025-07-30 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_test', '0002_alter_run_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
