# Generated by Django 5.2.4 on 2025-08-01 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_test', '0003_rule_remove_historicaltest_order_remove_test_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('rule_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_rules', to='llm_test.ruleversion')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='llm_test.run')),
            ],
            options={
                'unique_together': {('run', 'order'), ('run', 'rule_version')},
            },
        ),
        migrations.DeleteModel(
            name='TestVersionRule',
        ),
    ]
