# Generated by Django 5.2.4 on 2025-08-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_test', '0004_runrule_delete_testversionrule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='manual_check',
        ),
        migrations.AddField(
            model_name='runattempt',
            name='manual_check',
            field=models.BooleanField(default=False, help_text='Manual check of the response.'),
        ),
        migrations.DeleteModel(
            name='RunLog',
        ),
    ]
