# Generated by Django 5.2.4 on 2025-08-02 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_test', '0005_remove_run_manual_check_runattempt_manual_check_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='run',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='llm_test.rungroup'),
        ),
    ]
